/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <PWM_Motor.h>
#include <Clock_Motor.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <LCD.h>
#include <Timer_HE.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <inter_HE.h>
#include <UART.h>
#include <PWM_Servo.h>
#include <Clock_Servo.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <Pin_5_aliases.h>
#include <Pin_5.h>
#include <Pin_6_aliases.h>
#include <Pin_6.h>
#include <inter_horizontalSync.h>
#include <inter_verticalSync.h>
#include <inter_comparator.h>
#include <Timer_Nav.h>
#include <Clock_Nav.h>
#include <Pin_7_aliases.h>
#include <Pin_7.h>
#include <inter_infrared_rising_0.h>
#include <Timer_Infrared_0.h>
#include <Clock_Infrared.h>
#include <inter_infrared_falling_0.h>
#include <Pin_8_aliases.h>
#include <Pin_8.h>
#include <inter_infrared_rising_1.h>
#include <Timer_Infrared_1.h>
#include <inter_infrared_falling_1.h>
#include <Pin_9_aliases.h>
#include <Pin_9.h>
#include <inter_infrared_rising_2.h>
#include <Timer_Infrared_2.h>
#include <inter_infrared_falling_2.h>
#include <Pin_10_aliases.h>
#include <Pin_10.h>
#include <inter_infrared_rising_3.h>
#include <Timer_Infrared_3.h>
#include <inter_infrared_falling_3.h>
#include <Control_Reg.h>
#include <Pin_11_aliases.h>
#include <Pin_11.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
